Clojure 1.10.0-RC1
Look at the trace (Clojure version still 1.8) and see that GraalVM has filename based caching (oh oh). After renaming 1.10…

```
➜  closh git:(experiment/graal) ✗ rm -rf target; boot uberjar
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Compiling 1/23 clojure.tools.reader...
Compiling 2/23 clojure.tools.reader.default-data-readers...
Compiling 3/23 clojure.tools.reader.edn...
Compiling 4/23 clojure.tools.reader.impl.commons...
Compiling 5/23 clojure.tools.reader.impl.errors...
Compiling 6/23 clojure.tools.reader.impl.inspect...
Compiling 7/23 clojure.tools.reader.impl.utils...
Compiling 8/23 clojure.tools.reader.reader-types...
Compiling 9/23 closh.zero.builtin...
Compiling 10/23 closh.zero.compiler...
Compiling 11/23 closh.zero.core...
Compiling 12/23 closh.zero.env...
Compiling 13/23 closh.zero.frontend.main...
Compiling 14/23 closh.zero.frontend.rebel...
Compile time version  1.10.0-RC1
Compiling 15/23 closh.zero.macros...
Compiling 16/23 closh.zero.parser...
Compiling 17/23 closh.zero.pipeline...
Compiling 18/23 closh.zero.platform.io...
Compiling 19/23 closh.zero.platform.process...
Compiling 20/23 closh.zero.reader...
Compiling 21/23 closh.zero.service.completion...
Compiling 22/23 closh.zero.util...
Compiling 23/23 org.satta.glob...
Adding uberjar entries...
Writing project.jar...
Sifting output files...
Writing target dir(s)...
➜  closh git:(experiment/graal) ✗ ../graalvm-ee-1.0.0-rc7/Contents/Home/bin/native-image -jar target/project.jar
Build on Server(pid: 53049, port: 58011)
[project:53049]    classlist:   2,700.70 ms
[project:53049]        (cap):   1,271.06 ms
[project:53049]        setup:   1,671.52 ms
Compile time version  1.8.0
^C^C%                                                                                                                                                                                                       ➜  closh git:(experiment/graal) ✗ closh
Compile time version  1.10.0-RC1
Clojure version  1.10.0-RC1
$
➜  closh git:(experiment/graal) ✗ more
➜  closh git:(experiment/graal) ✗ rm -rf target; boot uberjar
^C%                                                                                                                                                                                                         ➜  closh git:(experiment/graal) ✗ rm -rf target; boot uberjar
Compiling 1/23 clojure.tools.reader...
Compiling 2/23 clojure.tools.reader.default-data-readers...
Compiling 3/23 clojure.tools.reader.edn...
Compiling 4/23 clojure.tools.reader.impl.commons...
Compiling 5/23 clojure.tools.reader.impl.errors...
Compiling 6/23 clojure.tools.reader.impl.inspect...
Compiling 7/23 clojure.tools.reader.impl.utils...
Compiling 8/23 clojure.tools.reader.reader-types...
Compiling 9/23 closh.zero.builtin...
Compiling 10/23 closh.zero.compiler...
Compiling 11/23 closh.zero.core...
Compiling 12/23 closh.zero.env...
Compiling 13/23 closh.zero.frontend.main...
Compiling 14/23 closh.zero.frontend.rebel...
Compile time version  1.10.0-RC1
Compiling 15/23 closh.zero.macros...
Compiling 16/23 closh.zero.parser...
Compiling 17/23 closh.zero.pipeline...
Compiling 18/23 closh.zero.platform.io...
Compiling 19/23 closh.zero.platform.process...
Compiling 20/23 closh.zero.reader...
Compiling 21/23 closh.zero.service.completion...
Compiling 22/23 closh.zero.util...
Compiling 23/23 org.satta.glob...
Adding uberjar entries...
Writing project.jar...
Sifting output files...
Writing target dir(s)...
➜  closh git:(experiment/graal) ✗ ../graalvm-ee-1.0.0-rc7/Contents/Home/bin/native-image -jar target/project.jar
Build on Server(pid: 53049, port: 58011)
[project:53049]    classlist:   2,287.36 ms
[project:53049]        (cap):   1,054.85 ms
[project:53049]        setup:   1,339.80 ms
Compile time version  1.8.0
^C^C%                                                                                                                                                                                                       ➜  closh git:(experiment/graal) ✗ mv target/project.jar target/project2.jar
➜  closh git:(experiment/graal) ✗ ../graalvm-ee-1.0.0-rc7/Contents/Home/bin/native-image -jar target/project2.jar
Build on Server(pid: 53049, port: 58011)
[project2:53049]    classlist:   2,333.87 ms
[project2:53049]        (cap):     673.11 ms
[project2:53049]        setup:     966.02 ms
Compile time version  1.10.0-RC1
[project2:53049]     analysis:  33,135.50 ms
error: unsupported features in 2 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported method java.lang.ClassLoader.defineClass(String, byte[], int, int) is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Trace:
	at parsing clojure.lang.DynamicClassLoader.defineClass(DynamicClassLoader.java:46)
Call path from entry point to clojure.lang.DynamicClassLoader.defineClass(String, byte[], Object):
	at clojure.lang.DynamicClassLoader.defineClass(DynamicClassLoader.java:45)
	at clojure.core$get_proxy_class.invokeStatic(core_proxy.clj:288)
	at clojure.core$get_proxy_class.doInvoke(core_proxy.clj:276)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at closh.zero.frontend.rebel.main(Unknown Source)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:163)
	at com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
Error: unbalanced monitors: mismatch at monitorexit, 96|LoadField#lockee__5436__auto__ != 3|LoadField#lockee__5436__auto__
Call path from entry point to clojure.spec.gen.alpha$dynaload$fn__2628.invoke():
	at clojure.spec.gen.alpha$dynaload$fn__2628.invoke(alpha.clj:21)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.Ref.applyTo(Ref.java:366)
	at closh.zero.frontend.rebel.main(Unknown Source)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:163)
	at com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
Original exception that caused the problem: org.graalvm.compiler.code.SourceStackTraceBailoutException$1: unbalanced monitors: mismatch at monitorexit, 96|LoadField#lockee__5436__auto__ != 3|LoadField#lockee__5436__auto__
	at clojure.spec.gen.alpha$dynaload$fn__2628.invoke(alpha.clj:22)
Caused by: org.graalvm.compiler.core.common.PermanentBailoutException: unbalanced monitors: mismatch at monitorexit, 96|LoadField#lockee__5436__auto__ != 3|LoadField#lockee__5436__auto__
	at org.graalvm.compiler.java.BytecodeParser.bailout(BytecodeParser.java:3602)
	at org.graalvm.compiler.java.BytecodeParser.genMonitorExit(BytecodeParser.java:2611)
	at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:4879)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3141)
	at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:2950)
	at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:888)
	at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:782)
	at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:95)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:204)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:323)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
	at com.oracle.graal.pointsto.flow.SpecialInvokeTypeFlow.onObservedUpdate(InvokeTypeFlow.java:421)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:347)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:389)
	at com.oracle.graal.pointsto.flow.SourceTypeFlowBase.update(SourceTypeFlowBase.java:121)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:508)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:174)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

Error: Processing image build request failed
➜  closh git:(experiment/graal) ✗ ../graalvm-ee-1.0.0-rc7/Contents/Home/bin/native-image -jar target/project.jar --report-unsupported-elements-at-runtime
Error: Invalid Path entry target/project.jar
Caused by: java.nio.file.NoSuchFileException: /Users/jeroen/bin/closh/target/project.jar
➜  closh git:(experiment/graal) ✗ ../graalvm-ee-1.0.0-rc7/Contents/Home/bin/native-image -jar target/project2.jar --report-unsupported-elements-at-runtime
Build on Server(pid: 53049, port: 58011)
[project2:53049]    classlist:   2,266.60 ms
[project2:53049]        (cap):   1,055.34 ms
[project2:53049]        setup:   1,348.99 ms
Compile time version  1.10.0-RC1
[project2:53049]     analysis:  23,653.48 ms
error: unbalanced monitors: mismatch at monitorexit, 96|LoadField#lockee__5436__auto__ != 3|LoadField#lockee__5436__auto__
Detailed message:
Error: unbalanced monitors: mismatch at monitorexit, 96|LoadField#lockee__5436__auto__ != 3|LoadField#lockee__5436__auto__
Call path from entry point to clojure.spec.gen.alpha$dynaload$fn__2628.invoke():
	at clojure.spec.gen.alpha$dynaload$fn__2628.invoke(alpha.clj:21)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:475)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:199)
	at com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eposix_002ethread_002ePosixJavaThreads_002epthreadStartRoutine_0028com_002eoracle_002esvm_002ecore_002ethread_002eJavaThreads_0024ThreadStartData_0029(generated:0)
Original exception that caused the problem: org.graalvm.compiler.code.SourceStackTraceBailoutException$1: unbalanced monitors: mismatch at monitorexit, 96|LoadField#lockee__5436__auto__ != 3|LoadField#lockee__5436__auto__
	at clojure.spec.gen.alpha$dynaload$fn__2628.invoke(alpha.clj:22)
Caused by: org.graalvm.compiler.core.common.PermanentBailoutException: unbalanced monitors: mismatch at monitorexit, 96|LoadField#lockee__5436__auto__ != 3|LoadField#lockee__5436__auto__
	at org.graalvm.compiler.java.BytecodeParser.bailout(BytecodeParser.java:3602)
	at org.graalvm.compiler.java.BytecodeParser.genMonitorExit(BytecodeParser.java:2611)
	at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:4879)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3141)
	at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:2950)
	at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:888)
	at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:782)
	at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:95)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:204)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:323)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
	at com.oracle.graal.pointsto.flow.SpecialInvokeTypeFlow.onObservedUpdate(InvokeTypeFlow.java:421)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:347)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:389)
	at com.oracle.graal.pointsto.flow.SourceTypeFlowBase.update(SourceTypeFlowBase.java:121)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:508)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:174)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

Error: Processing image build request failed
➜  closh git:(experiment/graal) ✗ closh
Error: Unable to access jarfile /Users/jeroen/bin/closh/target/project.jar
➜  closh git:(experiment/graal) ✗ mv target/project2.jar target/project.jar
➜  closh git:(experiment/graal) ✗ closh
Compile time version  1.10.0-RC1
Clojure version  1.10.0-RC1
$ (println "hi hi")
hi hi
$
```